version: "3"

services:
  mysqldb:
    image: mysql:8.0.36-debian
    container_name: mysqldb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQLDB_DATABASE_PASSWORD
      MYSQL_DATABASE: $MYSQLDB_DATABASE
      MYSQL_USER: $MYSQLDB_DATABASE_USERNAME
      MYSQL_PASSWORD: $MYSQLDB_DATABASE_PASSWORD
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql

  app:
    container_name: course-be
    build: .
    restart: always
    depends_on:
      mysqldb:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
volumes:
  db:


